import AsyncStorage from '@react-native-async-storage/async-storage';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useMemo, useState } from 'react';
import {
  Alert, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, Share,
  StatusBar as NativeStatusBar, StyleSheet, Switch, Text, TextInput, View,
} from 'react-native';
import { Audit, CartLine, categories, deals, fmtDate, initialStore, money, Movement, Notice, Person, Product, Purchase, Role, Sale, SaleLine, Store } from './src/model';

type IconName = React.ComponentProps<typeof MaterialCommunityIcons>['name'];
type Module = 'Dashboard' | 'Register' | 'AI Deals' | 'Products' | 'Inventory' | 'Orders' | 'Purchases' | 'Customers' | 'Reports' | 'Staff & Audit';
const modules: { name: Module; icon: IconName }[] = [
  { name: 'Dashboard', icon: 'view-dashboard-outline' }, { name: 'Register', icon: 'point-of-sale' },
  { name: 'AI Deals', icon: 'creation-outline' }, { name: 'Products', icon: 'shopping-outline' },
  { name: 'Inventory', icon: 'package-variant-closed' }, { name: 'Orders', icon: 'receipt-text-outline' },
  { name: 'Purchases', icon: 'truck-delivery-outline' }, { name: 'Customers', icon: 'account-group-outline' },
  { name: 'Reports', icon: 'chart-box-outline' }, { name: 'Staff & Audit', icon: 'shield-account-outline' },
];
const blue = '#1D4ED8';
const green = '#0F766E';
const amber = '#B45309';
const moneyRound = (n: number) => Number(n.toFixed(2));
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const daysUntil = (date?: string) => date ? Math.ceil((new Date(`${date}T23:59:59`).getTime() - Date.now()) / 86_400_000) : Infinity;
const divider = (color: string) => ({ height: StyleSheet.hairlineWidth, backgroundColor: color });

export default function App() {
  const [store, setStore] = useState<Store>(initialStore);
  const [loaded, setLoaded] = useState(false);
  const [user, setUser] = useState<Person | null>(null);
  const [tab, setTab] = useState<Module>('Dashboard');
  const [dark, setDark] = useState(false);
  const [cart, setCart] = useState<CartLine[]>([]);
  const [customer, setCustomer] = useState('Walk-in Customer');
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [inventoryFilter, setInventoryFilter] = useState('All');
  const [peopleTab, setPeopleTab] = useState<'Customers' | 'Suppliers'>('Customers');
  const [modal, setModal] = useState<'menu' | 'notifications' | 'checkout' | 'receipt' | 'form' | 'cart' | null>(null);
  const [formKind, setFormKind] = useState<'product' | 'customer' | 'supplier' | 'purchase' | 'staff'>('product');
  const [form, setForm] = useState<Record<string, string>>({});
  const [editingId, setEditingId] = useState<string | null>(null);
  const [payment, setPayment] = useState('CASH');
  const [tender, setTender] = useState('');
  const [cartDiscount, setCartDiscount] = useState(0);
  const [receipt, setReceipt] = useState<Sale | null>(null);
  const [query, setQuery] = useState('');
  const [messages, setMessages] = useState<{ user: boolean; text: string; dealIds?: string[] }[]>([
    { user: false, text: '👋 Assalam-o-alaikum! Main aapka POS offers assistant hoon. Deals, discounts, ya clearance ke baare mein poochiye.' },
  ]);
  const [loginName, setLoginName] = useState('admin');
  const [loginPin, setLoginPin] = useState('1234');
  const [loginError, setLoginError] = useState('');
  const [notificationsOpen, setNotificationsOpen] = useState(false);

  const darkMode = dark;
  const c = useMemo(() => darkMode ? {
    bg: '#0B0F19', surface: '#141C2E', raised: '#1E293B', text: '#F8FAFC', muted: '#CBD5E1', border: '#334155', primary: '#38BDF8', primarySoft: '#1E3A8A', success: '#2DD4BF', warn: '#FBBF24', danger: '#FB7185', onPrimary: '#03223F',
  } : {
    bg: '#F1F5F9', surface: '#FFFFFF', raised: '#E2E8F0', text: '#090D16', muted: '#475569', border: '#CBD5E1', primary: blue, primarySoft: '#DBEAFE', success: green, warn: amber, danger: '#DC2626', onPrimary: '#FFFFFF',
  }, [darkMode]);

  useEffect(() => {
    AsyncStorage.getItem('retail-pos-react-native-v1').then(value => {
      if (value) setStore(JSON.parse(value) as Store);
      setLoaded(true);
    }).catch(() => setLoaded(true));
  }, []);
  useEffect(() => {
    if (loaded) AsyncStorage.setItem('retail-pos-react-native-v1', JSON.stringify(store)).catch(() => {});
  }, [store, loaded]);

  const log = (action: string, details: string, by = user?.name || 'System') => {
    const event: Audit = { id: uid(), action, details, by, timestamp: new Date().toISOString() };
    setStore(prev => ({ ...prev, audits: [event, ...prev.audits] }));
  };
  const updateProduct = (id: string, patch: Partial<Product>) => setStore(prev => ({ ...prev, products: prev.products.map(p => p.id === id ? { ...p, ...patch } : p) }));
  const addLine = (product: Product, discount = product.discount || 0) => {
    if (product.stock <= 0) { Alert.alert('Out of stock', `${product.name} is not available right now.`); return; }
    setCart(prev => {
      const line = prev.find(item => item.productId === product.id);
      if (line) return prev.map(item => item.productId === product.id ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) } : item);
      return [...prev, { productId: product.id, quantity: 1, discount }];
    });
    setModal(null);
  };
  const changeQty = (productId: string, step: number) => setCart(prev => prev.map(line => line.productId === productId ? { ...line, quantity: line.quantity + step } : line).filter(line => line.quantity > 0 && (store.products.find(p => p.id === line.productId)?.stock || 0) >= line.quantity));
  const cartRows = cart.map(line => ({ line, product: store.products.find(product => product.id === line.productId)! })).filter(row => row.product);
  const subtotal = cartRows.reduce((sum, row) => sum + row.product.price * row.line.quantity, 0);
  const itemDiscount = cartRows.reduce((sum, row) => sum + row.product.price * row.line.quantity * row.line.discount / 100, 0);
  const beforeCartTax = subtotal - itemDiscount;
  const cartDiscountAmount = beforeCartTax * cartDiscount / 100;
  const taxTotal = cartRows.reduce((sum, row) => sum + row.product.price * row.line.quantity * (1 - row.line.discount / 100) * row.product.tax / 100, 0) * (1 - cartDiscount / 100);
  const total = Math.max(0, beforeCartTax - cartDiscountAmount + taxTotal);
  const unreadCount = store.notices.filter(n => !n.read).length;

  const authenticate = () => {
    const found = store.users.find(person => person.active !== false && (person.username?.toLowerCase() === loginName.trim().toLowerCase() || person.email?.toLowerCase() === loginName.trim().toLowerCase()) && person.pin === loginPin);
    if (!found) { setLoginError('Username or PIN is incorrect. Try admin / 1234.'); return; }
    setUser(found); setLoginError(''); setTab('Dashboard'); log('LOGIN', `${found.name} signed in`, found.name);
  };
  const goLogout = () => { if (user) log('LOGOUT', `${user.name} signed out`, user.name); setUser(null); setCart([]); setTab('Dashboard'); setModal(null); };

  const addToCartFromDeal = (dealId: string) => {
    const deal = deals.find(d => d.id === dealId);
    if (!deal) return;
    const products = deal.skus.map(sku => store.products.find(p => p.sku === sku)).filter((p): p is Product => Boolean(p));
    if (!products.length || products.some(p => p.stock <= 0)) { Alert.alert('Deal unavailable', 'One or more products in this bundle are out of stock.'); return; }
    setCart(prev => {
      const next = [...prev];
      for (const product of products) {
        const found = next.find(line => line.productId === product.id);
        if (found) found.quantity += 1;
        else next.push({ productId: product.id, quantity: 1, discount: deal.discount });
      }
      return next;
    });
    setTab('Register');
    Alert.alert('Bundle added', `${deal.title} added with ${deal.discount}% item discount.`);
  };
  const sendMessage = (text = query) => {
    const clean = text.trim(); if (!clean) return;
    const q = clean.toLowerCase();
    let selected = deals;
    if (q.includes('coffee') || q.includes('chai') || q.includes('beverage') || q.includes('tea')) selected = deals.filter(d => /coffee|beverage/i.test(`${d.title} ${d.category}`));
    else if (q.includes('tech') || q.includes('headphone') || q.includes('electronic')) selected = deals.filter(d => /tech|electronic/i.test(`${d.title} ${d.category}`));
    else if (q.includes('snack') || q.includes('chocolate') || q.includes('food')) selected = deals.filter(d => /snack|chocolate/i.test(`${d.title} ${d.category}`));
    else if (q.includes('health') || q.includes('wellness') || q.includes('vitamin')) selected = deals.filter(d => /wellness/i.test(`${d.title} ${d.category}`));
    else if (q.includes('clearance') || q.includes('expired') || q.includes('expiry')) {
      const near = store.products.filter(p => Number.isFinite(daysUntil(p.expiry)) && daysUntil(p.expiry) <= 30);
      setMessages(prev => [...prev, { user: true, text: clean }, { user: false, text: near.length ? `⚡ Clearance watch: ${near.map(p => `${p.name} (${p.stock} in stock, expires ${p.expiry})`).join(' · ')}. Manager se markdown approve karwa kar sale mein add karein.` : '✨ Koi item aglay 30 din mein expire nahi ho raha.' }]);
      setQuery(''); return;
    }
    const textReply = selected.length ? `✨ ${selected.length === deals.length ? 'Yeh active bundle deals abhi available hain:' : 'Aapke sawal ke liye yeh deals best hain:'} ${selected.map(d => `\n• ${d.title}: ${money(d.price)} (save ${d.discount}%)`).join('')}\n\n${selected[0].pitch}` : 'Aaj ke liye matching bundle nahi mila. Products tab mein catalog check karein.';
    setMessages(prev => [...prev, { user: true, text: clean }, { user: false, text: textReply, dealIds: selected.map(d => d.id) }]); setQuery('');
  };

  const finishSale = () => {
    if (!cartRows.length) { Alert.alert('Cart is empty', 'Add products before checkout.'); return; }
    const paid = payment === 'CASH' ? Number(tender || total) : total;
    if (paid < total) { Alert.alert('Payment incomplete', 'Cash tender cannot be less than the total.'); return; }
    if (cartRows.some(({ product, line }) => product.stock < line.quantity)) { Alert.alert('Stock changed', 'Please review the cart: one or more products no longer have enough stock.'); setModal(null); return; }
    const now = new Date().toISOString();
    const saleLines: SaleLine[] = cartRows.map(({ product, line }) => ({ name: product.name, sku: product.sku, quantity: line.quantity, price: product.price * (1 - line.discount / 100) }));
    const sale: Sale = { id: uid(), invoice: `POS-${10483 + store.sales.length}`, timestamp: now, customer, cashier: user?.name || 'Staff', subtotal: moneyRound(subtotal), discount: moneyRound(itemDiscount + cartDiscountAmount), tax: moneyRound(taxTotal), total: moneyRound(total), paid, change: Math.max(0, moneyRound(paid - total)), method: payment, status: 'COMPLETED', items: saleLines };
    setStore(prev => {
      const products = prev.products.map(product => {
        const line = cart.find(x => x.productId === product.id);
        if (!line) return product;
        const nextStock = product.stock - line.quantity;
        return { ...product, stock: nextStock };
      });
      const movements: Movement[] = cartRows.map(({ product, line }) => ({ id: uid(), product: product.name, delta: -line.quantity, reason: `Sale ${sale.invoice}`, by: user?.name || 'Staff', timestamp: now }));
      return { ...prev, products, sales: [sale, ...prev.sales], movements: [...movements, ...prev.movements], notices: products.filter(p => p.stock <= p.minimum).map(p => ({ id: uid(), title: `Low stock: ${p.name}`, body: `${p.stock} remaining · Minimum stock is ${p.minimum}`, read: false, timestamp: now })).concat(prev.notices).slice(0, 25) };
    });
    log('NEW SALE', `${sale.invoice} · ${money(sale.total)} · ${payment}`);
    setReceipt(sale); setCart([]); setCartDiscount(0); setCustomer('Walk-in Customer'); setModal('receipt');
  };
  const refundSale = (sale: Sale) => Alert.alert('Refund sale?', `Refund ${sale.invoice} for ${money(sale.total)} and restock the sold items?`, [
    { text: 'Cancel', style: 'cancel' }, { text: 'Refund', style: 'destructive', onPress: () => {
      const timestamp = new Date().toISOString();
      setStore(prev => {
        const products = prev.products.map(product => ({ ...product, stock: product.stock + (sale.items.find(item => item.sku === product.sku)?.quantity || 0) }));
        return { ...prev, products, sales: prev.sales.map(item => item.id === sale.id ? { ...item, status: 'REFUNDED' } : item), movements: [...sale.items.map(item => ({ id: uid(), product: item.name, delta: item.quantity, reason: `Refund ${sale.invoice}`, by: user?.name || 'Staff', timestamp })), ...prev.movements] };
      });
      log('REFUND', `${sale.invoice} · ${money(sale.total)}`);
    } },
  ]);

  const openForm = (kind: typeof formKind, item?: Product | Person) => {
    setFormKind(kind); setEditingId(item?.id || null);
    if (item && kind === 'product') {
      const product = item as Product; setForm({ name: product.name, sku: product.sku, category: product.category, brand: product.brand, cost: String(product.cost), price: String(product.price), tax: String(product.tax), stock: String(product.stock), minimum: String(product.minimum), expiry: product.expiry || '', batch: product.batch });
    } else if (item && kind === 'staff') {
      const person = item as Person; setForm({ name: person.name, username: person.username || '', pin: person.pin || '', role: person.role || 'CASHIER' });
    } else if (item && (kind === 'customer' || kind === 'supplier')) {
      const person = item as Person; setForm({ name: person.name, phone: person.phone, email: person.email, address: person.address });
    } else setForm(kind === 'product' ? { name: '', sku: '', category: 'Beverages', brand: '', cost: '', price: '', tax: '8', stock: '0', minimum: '5', expiry: '', batch: '' } : kind === 'purchase' ? { supplier: store.suppliers[0]?.name || '', sku: store.products[0]?.sku || '', quantity: '10', cost: String(store.products[0]?.cost || ''), status: 'RECEIVED' } : kind === 'staff' ? { name: '', username: '', pin: '', role: 'CASHIER' } : { name: '', phone: '', email: '', address: '' });
    setModal('form');
  };
  const saveForm = () => {
    if (formKind === 'product') {
      if (!form.name?.trim() || !form.sku?.trim() || !Number(form.price)) { Alert.alert('Required fields', 'Product name, SKU and price are required.'); return; }
      const product: Product = { id: editingId || uid(), name: form.name.trim(), sku: form.sku.trim(), category: form.category || 'Other', brand: form.brand || '—', cost: Number(form.cost) || 0, price: Number(form.price), tax: Number(form.tax) || 0, stock: Number(form.stock) || 0, minimum: Number(form.minimum) || 0, expiry: form.expiry || undefined, batch: form.batch || '—' };
      setStore(prev => ({ ...prev, products: editingId ? prev.products.map(p => p.id === editingId ? product : p) : [product, ...prev.products] })); log(editingId ? 'EDIT PRODUCT' : 'ADD PRODUCT', product.name); setModal(null); return;
    }
    if (formKind === 'purchase') {
      const product = store.products.find(p => p.sku === form.sku) || store.products[0]; const quantity = Number(form.quantity) || 1; const cost = Number(form.cost) || product.cost;
      const purchase: Purchase = { id: uid(), number: `PO-${String(243 + store.purchases.length).padStart(5, '0')}`, supplier: form.supplier || 'Supplier', timestamp: new Date().toISOString(), total: moneyRound(quantity * cost), status: form.status === 'PENDING' ? 'PENDING' : 'RECEIVED', items: [{ productId: product.id, quantity, cost }] };
      setStore(prev => ({ ...prev, purchases: [purchase, ...prev.purchases], products: purchase.status === 'RECEIVED' ? prev.products.map(p => p.id === product.id ? { ...p, stock: p.stock + quantity, cost } : p) : prev.products, movements: purchase.status === 'RECEIVED' ? [{ id: uid(), product: product.name, delta: quantity, reason: `Purchase ${purchase.number}`, by: user?.name || 'Staff', timestamp: purchase.timestamp }, ...prev.movements] : prev.movements })); log('NEW PURCHASE', `${purchase.number} · ${purchase.status}`); setModal(null); return;
    }
    if (!form.name?.trim()) { Alert.alert('Name required', 'Please enter a name.'); return; }
    if (formKind === 'staff') {
      const person: Person = { id: editingId || uid(), name: form.name, username: form.username, email: form.username, phone: form.username, address: form.role || 'CASHIER', pin: form.pin || '1234', role: (form.role || 'CASHIER') as Role, active: true, totalSpent: 0 };
      setStore(prev => ({ ...prev, users: editingId ? prev.users.map(p => p.id === editingId ? person : p) : [person, ...prev.users] })); log(editingId ? 'EDIT USER' : 'ADD USER', `${person.name} (${person.role})`); setModal(null); return;
    }
    const person: Person = { id: editingId || uid(), name: form.name, phone: form.phone || '', email: form.email || '', address: form.address || '', totalSpent: 0 };
    if (formKind === 'customer') setStore(prev => ({ ...prev, customers: editingId ? prev.customers.map(p => p.id === editingId ? person : p) : [person, ...prev.customers] }));
    else setStore(prev => ({ ...prev, suppliers: editingId ? prev.suppliers.map(p => p.id === editingId ? person : p) : [person, ...prev.suppliers] }));
    log(`ADD ${formKind.toUpperCase()}`, person.name); setModal(null);
  };
  const receivePurchase = (purchase: Purchase) => {
    setStore(prev => ({ ...prev, purchases: prev.purchases.map(p => p.id === purchase.id ? { ...p, status: 'RECEIVED' } : p), products: prev.products.map(product => { const item = purchase.items.find(i => i.productId === product.id); return item ? { ...product, stock: product.stock + item.quantity, cost: item.cost } : product; }), movements: [...purchase.items.map(i => ({ id: uid(), product: store.products.find(p => p.id === i.productId)?.name || 'Product', delta: i.quantity, reason: `Purchase ${purchase.number}`, by: user?.name || 'Staff', timestamp: new Date().toISOString() })), ...prev.movements] })); log('PURCHASE RECEIVED', purchase.number);
  };
  const stockAdjust = (product: Product, delta: number) => {
    const reason = delta < 0 ? 'Manual write-off / disposal' : 'Manual stock adjustment';
    setStore(prev => ({ ...prev, products: prev.products.map(p => p.id === product.id ? { ...p, stock: Math.max(0, p.stock + delta) } : p), movements: [{ id: uid(), product: product.name, delta, reason, by: user?.name || 'Staff', timestamp: new Date().toISOString() }, ...prev.movements] })); log('STOCK ADJUSTMENT', `${product.name} · ${delta > 0 ? '+' : ''}${delta}`);
  };

  if (!user) return <View style={[s.root, { backgroundColor: c.bg }]}><StatusBar style={darkMode ? 'light' : 'dark'} /><Login c={c} loginName={loginName} loginPin={loginPin} setLoginName={setLoginName} setLoginPin={setLoginPin} error={loginError} onLogin={authenticate} dark={dark} setDark={setDark} /></View>;

  const headerTitle = tab === 'Register' ? 'POS Register' : tab;
  const filteredProducts = store.products.filter(p => (category === 'All' || p.category === category) && `${p.name} ${p.sku} ${p.brand}`.toLowerCase().includes(search.toLowerCase()));
  const lowStock = store.products.filter(p => p.stock <= p.minimum);
  const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0);
  const todaySales = store.sales.filter(sale => new Date(sale.timestamp) >= todayStart && sale.status !== 'REFUNDED');
  const todayRevenue = todaySales.reduce((sum, sale) => sum + sale.total, 0);
  const todayCount = todaySales.length;
  const unread = unreadCount;

  const setField = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  const field = (label: string, key: string, keyboard: 'default' | 'numeric' = 'default', placeholder = '') => <View style={{ marginBottom: 12 }} key={key}><Text style={[s.fieldLabel, { color: c.muted }]}>{label}</Text><TextInput value={form[key] || ''} onChangeText={value => setField(key, value)} keyboardType={keyboard === 'numeric' ? 'decimal-pad' : 'default'} placeholder={placeholder || label} placeholderTextColor={c.muted} style={[s.input, { backgroundColor: c.bg, borderColor: c.border, color: c.text }]} /></View>;
  const showForm = (kind: typeof formKind, item?: Product | Person) => openForm(kind, item);

  const dashboardScreen = () => <>
    <View style={s.storeHeadline}><View style={{ flex: 1 }}><Text style={[s.eyebrow, { color: c.muted }]}>DOWNTOWN TERMINAL  ·  #104</Text><Text style={[s.bigTitle, { color: c.text }]}>Good morning, {user.name.split(' ')[0]}</Text><Text style={[s.subText, { color: c.muted }]}>Here’s your store at a glance.</Text></View><Pressable onPress={() => setModal('notifications')} style={[s.iconBtn, { backgroundColor: c.surface }]}><Icon c={c} name="bell-outline" size={21} /><View style={s.notificationDot}><Text style={s.dotText}>{unread}</Text></View></Pressable></View>
    <View style={s.metricGrid}>
      <Metric c={c} icon="cash-multiple" label="Today's sales" value={money(todayRevenue || 2486.42)} delta="+12.8% vs yesterday" tint="#DBEAFE" onPress={() => setTab('Reports')} />
      <Metric c={c} icon="receipt-text-outline" label="Transactions" value={String(todayCount || 38)} delta="4 awaiting review" tint="#CCFBF1" onPress={() => setTab('Orders')} />
      <Metric c={c} icon="package-variant-closed" label="Low stock" value={String(lowStock.length)} delta="Needs attention" tint="#FEF3C7" onPress={() => { setInventoryFilter('Low stock'); setTab('Inventory'); }} />
      <Metric c={c} icon="chart-line" label="Est. net profit" value={money(todaySales.length ? todayRevenue * 0.31 : 771.18)} delta="31.0% margin" tint="#EDE9FE" onPress={() => setTab('Reports')} />
    </View>
    <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Quick actions</Text><Text style={[s.link, { color: c.primary }]} onPress={() => setModal('menu')}>All tools</Text></View>
    <View style={s.quickGrid}>{[['Register', 'point-of-sale', '#DBEAFE'], ['Add product', 'plus-box-outline', '#CCFBF1'], ['New purchase', 'truck-plus-outline', '#FEF3C7'], ['Reports', 'chart-box-outline', '#EDE9FE']].map(([label, icon, tint]) => <Pressable key={label} onPress={() => label === 'Register' ? setTab('Register') : label === 'Add product' ? showForm('product') : label === 'New purchase' ? showForm('purchase') : setTab('Reports')} style={[s.quickAction, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.iconSquare, { backgroundColor: tint }]}><Icon c={c} name={icon as IconName} color={blue} /></View><Text style={[s.quickText, { color: c.text }]}>{label}</Text><Icon c={c} name="chevron-right" color={c.muted} size={18} /></Pressable>)}</View>
    <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Sales overview</Text><Pressable onPress={() => setTab('Reports')}><Text style={[s.link, { color: c.primary }]}>View report</Text></Pressable></View>
    <View style={[s.chartCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={s.chartTop}><View><Text style={[s.cardLabel, { color: c.muted }]}>Gross revenue</Text><Text style={[s.chartAmount, { color: c.text }]}>{money(todayRevenue || 2486.42)}</Text></View><View style={[s.pill, { backgroundColor: '#DCFCE7' }]}><Text style={{ color: '#15803D', fontSize: 11, fontWeight: '800' }}>↗ 12.8%</Text></View></View><View style={s.chartBars}>{[38, 54, 42, 68, 56, 82, 65, 93, 60, 76, 48, 88, 63, 100, 74, 90, 57, 78, 49, 86, 67, 94, 59, 82].map((height, i) => <View key={i} style={{ flex: 1, justifyContent: 'flex-end' }}><View style={{ height: `${height}%`, borderRadius: 4, backgroundColor: i > 19 ? c.primary : c.primarySoft, opacity: i > 19 ? 1 : 0.6 }} /></View>)}</View><View style={s.chartLabels}><Text style={[s.mini, { color: c.muted }]}>8 AM</Text><Text style={[s.mini, { color: c.muted }]}>12 PM</Text><Text style={[s.mini, { color: c.muted }]}>4 PM</Text><Text style={[s.mini, { color: c.muted }]}>8 PM</Text></View></View>
    <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Recent sales</Text><Pressable onPress={() => setTab('Orders')}><Text style={[s.link, { color: c.primary }]}>See all</Text></Pressable></View>
    {store.sales.slice(0, 4).map(sale => <SaleRow key={sale.id} c={c} sale={sale} />)}
    <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Stock alerts</Text><Pressable onPress={() => setTab('Inventory')}><Text style={[s.link, { color: c.primary }]}>Review stock</Text></Pressable></View>
    {lowStock.slice(0, 3).map(product => <ProductRow key={product.id} c={c} product={product} trailing={<Pressable onPress={() => stockAdjust(product, 5)} style={[s.tinyAction, { backgroundColor: c.primarySoft }]}><Text style={[s.tinyActionText, { color: c.primary }]}>+ Restock</Text></Pressable>} />)}
  </>;

  const registerScreen = () => <>
    <View style={[s.customerSelector, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.avatar, { backgroundColor: '#DBEAFE' }]}><Icon c={c} name="account-outline" color={blue} /></View><View style={{ flex: 1 }}><Text style={[s.mini, { color: c.muted }]}>CUSTOMER</Text><Text style={[s.rowTitle, { color: c.text }]}>{customer}</Text></View><Pressable onPress={() => Alert.alert('Select customer', ['Walk-in Customer', ...store.customers.map(x => x.name)].join('\n\n'), [{ text: 'Walk-in', onPress: () => setCustomer('Walk-in Customer') }, ...store.customers.slice(0, 3).map(x => ({ text: x.name, onPress: () => setCustomer(x.name) }))])}><Text style={[s.link, { color: c.primary }]}>Change</Text></Pressable></View>
    <SearchBox c={c} value={search} onChange={setSearch} placeholder="Search products or scan barcode" />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chipsRow}>{categories.map(item => <Chip key={item} c={c} active={item === category} label={item} onPress={() => setCategory(item)} />)}</ScrollView>
    <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Popular products</Text><Pressable onPress={() => setModal('cart')}><Text style={[s.link, { color: c.primary }]}>Cart · {cart.reduce((sum, item) => sum + item.quantity, 0)}</Text></Pressable></View>
    <View style={s.productGrid}>{filteredProducts.map(product => <Pressable key={product.id} onPress={() => addLine(product)} style={[s.productTile, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.productEmoji, { backgroundColor: product.category === 'Beverages' ? '#DBEAFE' : product.category === 'Electronics' ? '#EDE9FE' : '#CCFBF1' }]}><Text style={{ fontSize: 29 }}>{product.category === 'Beverages' ? '☕' : product.category === 'Electronics' ? '🎧' : product.category === 'Dairy & Fresh' ? '🥛' : product.category === 'Snacks' ? '🍫' : product.category === 'Health & Wellness' ? '🌿' : '🛍️'}</Text></View><Text style={[s.productName, { color: c.text }]} numberOfLines={2}>{product.name}</Text><Text style={[s.mini, { color: c.muted }]}>{product.stock} in stock</Text><View style={s.productTileFoot}><Text style={[s.productPrice, { color: c.primary }]}>{money(product.price)}</Text><View style={[s.plusCircle, { backgroundColor: c.primary }]}><Icon c={c} name="plus" color="#fff" size={16} /></View></View></Pressable>)}</View>
    <View style={{ height: 16 }} />
  </>;

  const productScreen = () => <>
    <View style={s.sectionHead}><Text style={[s.subText, { color: c.muted }]}>{store.products.length} products in catalog</Text><Pressable onPress={() => showForm('product')} style={[s.primaryAction, { backgroundColor: c.primary }]}><Icon c={c} name="plus" color="#fff" size={16} /><Text style={s.primaryActionText}>Add product</Text></Pressable></View>
    <SearchBox c={c} value={search} onChange={setSearch} placeholder="Search name, SKU or brand" />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chipsRow}>{categories.map(item => <Chip key={item} c={c} active={item === category} label={item} onPress={() => setCategory(item)} />)}</ScrollView>
    {filteredProducts.map(product => <ProductRow key={product.id} c={c} product={product} trailing={<Pressable onPress={() => showForm('product', product)} style={[s.iconBtnSmall, { backgroundColor: c.bg }]}><Icon c={c} name="pencil-outline" size={17} /></Pressable>} onPress={() => Alert.alert(product.name, `SKU ${product.sku}\n${product.brand} · ${product.category}\nCost ${money(product.cost)} · Retail ${money(product.price)}\nStock ${product.stock} · Min ${product.minimum}\nBatch ${product.batch}${product.expiry ? ` · Expiry ${product.expiry}` : ''}`)} />)}
  </>;

  const inventoryScreen = () => {
    const rows = store.products.filter(p => inventoryFilter === 'All' || (inventoryFilter === 'Low stock' && p.stock > 0 && p.stock <= p.minimum) || (inventoryFilter === 'Out of stock' && p.stock === 0) || (inventoryFilter === 'Expired' && daysUntil(p.expiry) < 0) || (inventoryFilter === 'Expiring soon' && daysUntil(p.expiry) >= 0 && daysUntil(p.expiry) <= 30));
    return <><View style={s.inventoryTotals}>{[[String(store.products.reduce((sum, p) => sum + p.stock, 0)), 'UNITS ON HAND'], [String(lowStock.length), 'LOW STOCK'], [String(store.products.filter(p => daysUntil(p.expiry) < 0).length), 'EXPIRED ITEMS']].map(([v, label]) => <View key={label} style={[s.inventoryTotal, { backgroundColor: c.surface, borderColor: c.border }]}><Text style={[s.metricValue, { color: c.text }]}>{v}</Text><Text style={[s.mini, { color: c.muted }]}>{label}</Text></View>)}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chipsRow}>{['All', 'Low stock', 'Out of stock', 'Expiring soon', 'Expired'].map(item => <Chip key={item} c={c} active={inventoryFilter === item} label={item} onPress={() => setInventoryFilter(item)} />)}</ScrollView><View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Stock levels</Text><Text style={[s.mini, { color: c.muted }]}>Sorted by alert status</Text></View>{rows.map(product => { const expired = daysUntil(product.expiry) < 0; const near = daysUntil(product.expiry) >= 0 && daysUntil(product.expiry) <= 30; return <ProductRow key={product.id} c={c} product={product} trailing={<View style={{ alignItems: 'flex-end' }}><Text style={[s.stockTag, { color: product.stock === 0 || expired ? c.danger : product.stock <= product.minimum ? c.warn : c.success }]}>{expired ? 'EXPIRED' : product.stock === 0 ? 'OUT' : product.stock <= product.minimum ? 'LOW' : 'HEALTHY'}</Text><View style={s.stockActions}><Pressable onPress={() => stockAdjust(product, -1)} style={[s.stepButton, { backgroundColor: c.bg }]}><Icon c={c} name="minus" size={16} /></Pressable><Pressable onPress={() => stockAdjust(product, 1)} style={[s.stepButton, { backgroundColor: c.primarySoft }]}><Icon c={c} name="plus" color={c.primary} size={16} /></Pressable></View></View>} subline={`SKU ${product.sku} · Min ${product.minimum}${product.expiry ? ` · ${near || expired ? (expired ? 'Expired' : `Expires ${product.expiry}`) : `Expiry ${product.expiry}`}` : ''}`} />; })}{rows.length === 0 && <Empty c={c} title="No items in this view" text="There are no products matching this inventory filter." />}</>;
  };

  const aiScreen = () => <><View style={[s.aiBanner, { backgroundColor: c.primarySoft }]}><View style={[s.iconSquare, { backgroundColor: c.surface }]}><Icon c={c} name="creation" color={c.primary} /></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>Retail POS Genius</Text><Text style={[s.mini, { color: c.muted }]}>Offline offers assistant · Roman Urdu supported</Text></View><View style={[s.pill, { backgroundColor: '#DCFCE7' }]}><Text style={{ color: '#15803D', fontWeight: '800', fontSize: 10 }}>● ONLINE</Text></View></View><View style={s.chipsRow}>{['New offers', 'Coffee deals', 'Clearance'].map((item, i) => <Chip key={item} c={c} label={item} active={false} onPress={() => sendMessage(i === 0 ? 'What offers are active?' : i === 1 ? 'Coffee deals dikhao' : 'Show clearance items')} />)}</View><View style={[s.chatBox, { backgroundColor: c.surface, borderColor: c.border }]}>{messages.map((message, index) => <View key={index} style={[s.chatBubble, message.user ? { alignSelf: 'flex-end', backgroundColor: c.primary } : { alignSelf: 'flex-start', backgroundColor: c.bg, borderColor: c.border }]}><Text style={{ color: message.user ? '#fff' : c.text, fontSize: 13, lineHeight: 19 }}>{message.text}</Text>{!message.user && message.dealIds?.map(id => { const deal = deals.find(d => d.id === id)!; return <View key={id} style={[s.dealMini, { borderColor: c.border, backgroundColor: c.surface }]}><Text style={[s.rowTitle, { color: c.text, flex: 1 }]}>{deal.title}</Text><Text style={[s.rowTitle, { color: c.primary }]}>{money(deal.price)}</Text><Pressable style={[s.addDealBtn, { backgroundColor: c.primary }]} onPress={() => addToCartFromDeal(id)}><Text style={s.primaryActionText}>Add to cart</Text></Pressable></View>; })}</View>)}</View><View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Active bundle deals</Text><Text style={[s.mini, { color: c.muted }]}>{deals.length} available</Text></View>{deals.map(deal => <View key={deal.id} style={[s.dealCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={s.dealCardTop}><View style={[s.iconSquare, { backgroundColor: '#FEF3C7' }]}><Icon c={c} name="tag-heart-outline" color={amber} /></View><View style={{ flex: 1 }}><Text style={[s.mini, { color: c.primary, fontWeight: '800' }]}>{deal.category.toUpperCase()} · SAVE {deal.discount}%</Text><Text style={[s.rowTitle, { color: c.text }]}>{deal.title}</Text></View></View><Text style={[s.subText, { color: c.muted }]}>{deal.pitch}</Text><View style={s.dealFoot}><Text style={[s.mini, { color: c.muted, textDecorationLine: 'line-through' }]}>{money(deal.original)}</Text><Text style={[s.productPrice, { color: c.text }]}>{money(deal.price)}</Text><Pressable onPress={() => addToCartFromDeal(deal.id)} style={[s.primaryAction, { backgroundColor: c.primary }]}><Icon c={c} name="cart-plus" color="#fff" size={16} /><Text style={s.primaryActionText}>Add bundle</Text></Pressable></View></View>)}</>;

  const orderScreen = () => <>{store.sales.map(sale => <SaleRow key={sale.id} c={c} sale={sale} trailing={sale.status === 'COMPLETED' && user.role !== 'CASHIER' ? <Pressable onPress={() => refundSale(sale)} style={[s.iconBtnSmall, { backgroundColor: '#FEE2E2' }]}><Icon c={c} name="backup-restore" color="#B91C1C" size={17} /></Pressable> : <Icon c={c} name="chevron-right" />} onPress={() => Alert.alert(sale.invoice, `${sale.customer} · ${fmtDate(sale.timestamp)}\n${sale.items.map(item => `${item.quantity} × ${item.name}`).join('\n')}\n\nSubtotal ${money(sale.subtotal)} · Tax ${money(sale.tax)}\n${sale.method} · Total ${money(sale.total)}${sale.status === 'REFUNDED' ? '\nREFUNDED' : ''}`)} />)}</>;

  const purchaseScreen = () => <><View style={s.sectionHead}><Text style={[s.subText, { color: c.muted }]}>{store.purchases.length} purchase orders</Text><Pressable onPress={() => showForm('purchase')} style={[s.primaryAction, { backgroundColor: c.primary }]}><Icon c={c} name="plus" color="#fff" size={16} /><Text style={s.primaryActionText}>New purchase</Text></Pressable></View>{store.purchases.map(purchase => <View key={purchase.id} style={[s.listCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={s.listCardTop}><View style={[s.iconSquare, { backgroundColor: '#FEF3C7' }]}><Icon c={c} name="truck-delivery-outline" color={amber} /></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{purchase.supplier}</Text><Text style={[s.mini, { color: c.muted }]}>{purchase.number} · {fmtDate(purchase.timestamp)}</Text></View><Badge label={purchase.status} good={purchase.status === 'RECEIVED'} c={c} /></View><View style={divider(c.border)} /><View style={s.rowBetween}><View><Text style={[s.mini, { color: c.muted }]}>{purchase.items.length || '—'} line items</Text><Text style={[s.productPrice, { color: c.text }]}>{money(purchase.total)}</Text></View>{purchase.status === 'PENDING' && <Pressable onPress={() => receivePurchase(purchase)} style={[s.primaryAction, { backgroundColor: c.success }]}><Icon c={c} name="check" color="#fff" size={16} /><Text style={s.primaryActionText}>Receive stock</Text></Pressable>}</View></View>)}</>;

  const customersScreen = () => {
    const list = peopleTab === 'Customers' ? store.customers : store.suppliers;
    return <><View style={[s.segment, { backgroundColor: c.raised }]}>{(['Customers', 'Suppliers'] as const).map(item => <Pressable key={item} onPress={() => setPeopleTab(item)} style={[s.segmentItem, item === peopleTab && { backgroundColor: c.surface }]}><Text style={[s.segmentText, { color: item === peopleTab ? c.text : c.muted }]}>{item} ({item === 'Customers' ? store.customers.length : store.suppliers.length})</Text></Pressable>)}</View><View style={s.sectionHead}><Text style={[s.subText, { color: c.muted }]}>Relationship directory</Text><Pressable onPress={() => showForm(peopleTab === 'Customers' ? 'customer' : 'supplier')} style={[s.primaryAction, { backgroundColor: c.primary }]}><Icon c={c} name="plus" color="#fff" size={16} /><Text style={s.primaryActionText}>Add {peopleTab === 'Customers' ? 'customer' : 'supplier'}</Text></Pressable></View>{list.map(person => <View key={person.id} style={[s.personCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.avatar, { backgroundColor: peopleTab === 'Customers' ? '#DBEAFE' : '#CCFBF1' }]}><Text style={{ color: peopleTab === 'Customers' ? blue : green, fontWeight: '800' }}>{person.name.split(' ').map(p => p[0]).join('').slice(0, 2)}</Text></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{person.name}</Text><Text style={[s.mini, { color: c.muted }]}>{person.phone || 'No phone'}{person.email ? ` · ${person.email}` : ''}</Text><Text style={[s.mini, { color: c.muted }]}>{person.address || 'No address'}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={[s.mini, { color: c.muted }]}>{peopleTab === 'Customers' ? 'LIFETIME' : 'PURCHASES'}</Text><Text style={[s.rowTitle, { color: c.primary }]}>{money(person.totalSpent)}</Text><Pressable onPress={() => showForm(peopleTab === 'Customers' ? 'customer' : 'supplier', person)}><Text style={[s.link, { color: c.primary, marginTop: 6 }]}>Edit</Text></Pressable></View></View>)}</>;
  };

  const reportScreen = () => {
    const completed = store.sales.filter(s => s.status === 'COMPLETED');
    const gross = completed.reduce((sum, s) => sum + s.total, 0);
    const cash = completed.filter(s => s.method === 'CASH').reduce((sum, s) => sum + s.total, 0);
    const card = completed.filter(s => s.method === 'CARD').reduce((sum, s) => sum + s.total, 0);
    const margin = completed.reduce((sum, sale) => sum + sale.items.reduce((itemSum, item) => { const product = store.products.find(p => p.sku === item.sku); return itemSum + (item.price - (product?.cost || 0)) * item.quantity; }, 0), 0);
    return <><View style={s.chipsRow}>{['Today', '7 days', '30 days'].map(item => <Chip key={item} c={c} active={item === 'Today'} label={item} onPress={() => {}} />)}</View><View style={[s.reportHero, { backgroundColor: c.primary }]}><Text style={{ color: '#DBEAFE', fontWeight: '700', fontSize: 12 }}>TOTAL GROSS SALES</Text><Text style={{ color: '#fff', fontSize: 34, fontWeight: '900', marginTop: 6 }}>{money(gross || 2486.42)}</Text><Text style={{ color: '#DBEAFE', marginTop: 7, fontSize: 12 }}>{completed.length || 38} completed transactions · Today</Text></View><View style={s.metricGrid}><Metric c={c} icon="chart-line" label="Est. gross profit" value={money(margin || gross * .31 || 771.18)} delta="Before operating costs" tint="#CCFBF1" /><Metric c={c} icon="ticket-percent-outline" label="Average sale" value={money(completed.length ? gross / completed.length : 65.43)} delta="Per transaction" tint="#EDE9FE" /></View><View style={[s.listCard, { backgroundColor: c.surface, borderColor: c.border }]}><Text style={[s.sectionTitle, { color: c.text, marginBottom: 14 }]}>Payment breakdown</Text><ProgressLine c={c} title="Cash" total={cash || 1243.21} maximum={gross || 2486.42} tint={c.primary} /><ProgressLine c={c} title="Card" total={card || 996.84} maximum={gross || 2486.42} tint={green} /><ProgressLine c={c} title="Wallet / other" total={Math.max(0, gross - cash - card) || 246.37} maximum={gross || 2486.42} tint={amber} /></View><View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Best sellers</Text><Pressable onPress={() => Share.share({ title: 'POS sales report', message: `Retail POS · Sales summary\nRevenue: ${money(gross)}\nTransactions: ${completed.length}\nEstimated profit: ${money(margin)}` })}><Text style={[s.link, { color: c.primary }]}>Export / share</Text></Pressable></View>{store.products.slice().sort((a, b) => b.price - a.price).slice(0, 4).map(product => <ProductRow key={product.id} c={c} product={product} subline={`${product.category} · ${product.stock} in stock`} trailing={<Text style={[s.rowTitle, { color: c.primary }]}>{money(product.price)}</Text>} />)}<View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Sales by day</Text></View><View style={[s.listCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={s.chartBars}>{[58, 72, 48, 82, 66, 91, 75].map((h, i) => <View key={i} style={{ flex: 1, alignItems: 'center', justifyContent: 'flex-end' }}><View style={{ width: 20, height: h, borderRadius: 6, backgroundColor: i === 6 ? c.primary : c.primarySoft }} /><Text style={[s.mini, { color: c.muted, marginTop: 6 }]}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</Text></View>)}</View></View></>;
  };

  const staffScreen = () => <>{user.role !== 'ADMIN' ? <Empty c={c} title="Admin access required" text="Staff and audit records are only visible to an admin." /> : <><View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Team members</Text><Pressable onPress={() => showForm('staff')} style={[s.primaryAction, { backgroundColor: c.primary }]}><Icon c={c} name="account-plus-outline" color="#fff" size={16} /><Text style={s.primaryActionText}>Add staff</Text></Pressable></View>{store.users.map(person => <View key={person.id} style={[s.personCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.avatar, { backgroundColor: '#DBEAFE' }]}><Icon c={c} name="account-outline" color={blue} /></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{person.name}</Text><Text style={[s.mini, { color: c.muted }]}>{person.username} · PIN {person.pin} · {person.address}</Text></View><Badge label={person.role || 'CASHIER'} good={person.role === 'ADMIN'} c={c} /></View>)}<View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>Audit trail</Text><Text style={[s.mini, { color: c.muted }]}>{store.audits.length} records</Text></View>{store.audits.slice(0, 35).map(event => <View key={event.id} style={[s.auditRow, { borderColor: c.border }]}><View style={[s.auditBullet, { backgroundColor: c.primary }]} /><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{event.action}</Text><Text style={[s.mini, { color: c.muted }]}>{event.details}</Text><Text style={[s.mini, { color: c.muted }]}>{event.by} · {fmtDate(event.timestamp)}</Text></View></View>)}</>}</>;

  const content = tab === 'Dashboard' ? dashboardScreen() : tab === 'Register' ? registerScreen() : tab === 'AI Deals' ? aiScreen() : tab === 'Products' ? productScreen() : tab === 'Inventory' ? inventoryScreen() : tab === 'Orders' ? orderScreen() : tab === 'Purchases' ? purchaseScreen() : tab === 'Customers' ? customersScreen() : tab === 'Reports' ? reportScreen() : staffScreen();
  const formFields = formKind === 'product' ? [['Product name', 'name'], ['SKU / Barcode', 'sku'], ['Category', 'category'], ['Brand', 'brand'], ['Cost price', 'cost', 'numeric'], ['Retail price', 'price', 'numeric'], ['Tax %', 'tax', 'numeric'], ['Stock on hand', 'stock', 'numeric'], ['Minimum stock alert', 'minimum', 'numeric'], ['Expiry date (YYYY-MM-DD)', 'expiry'], ['Batch number', 'batch']] : formKind === 'purchase' ? [['Supplier', 'supplier'], ['Product SKU', 'sku'], ['Quantity', 'quantity', 'numeric'], ['Unit cost', 'cost', 'numeric']] : formKind === 'staff' ? [['Full name', 'name'], ['Username', 'username'], ['PIN', 'pin', 'numeric'], ['Role (ADMIN / MANAGER / CASHIER)', 'role']] : [['Full name', 'name'], ['Phone', 'phone'], ['Email', 'email'], ['Address', 'address']];
  const hideMenu = () => setModal(null);

  return <View style={[s.root, { backgroundColor: c.bg }]}><StatusBar style={darkMode ? 'light' : 'dark'} />
    <View style={[s.topBar, { backgroundColor: c.surface, borderColor: c.border }]}><Pressable onPress={() => setModal('menu')} style={[s.menuBtn, { backgroundColor: c.primarySoft }]}><Icon c={c} name="storefront-outline" color={c.primary} size={22} /></Pressable><View style={{ flex: 1 }}><Text style={[s.topTitle, { color: c.text }]}>{headerTitle}</Text><Text style={[s.topSubtitle, { color: c.muted }]}>{user.name} · {user.role}</Text></View><Pressable onPress={() => setModal('notifications')} style={[s.iconBtnSmall, { backgroundColor: c.bg }]}><Icon c={c} name="bell-outline" size={19} /><View style={[s.smallDot, { backgroundColor: c.danger }]} /></Pressable><Pressable onPress={() => setDark(!dark)} style={[s.iconBtnSmall, { backgroundColor: c.bg }]}><Icon c={c} name={dark ? 'weather-sunny' : 'weather-night'} size={18} /></Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.scrollContent} showsVerticalScrollIndicator={false}>{tab !== 'Dashboard' && <View style={s.pageHeading}><Text style={[s.pageTitle, { color: c.text }]}>{tab}</Text><Text style={[s.subText, { color: c.muted }]}>{tab === 'Register' ? 'Search, scan and add items to this sale.' : tab === 'Inventory' ? 'Stock levels, expiry dates and adjustments.' : tab === 'AI Deals' ? 'Offers finder for your sales team.' : tab === 'Products' ? 'Catalog, prices and product details.' : tab === 'Orders' ? 'Receipts, returns and transaction history.' : tab === 'Purchases' ? 'Supplier orders and stock receiving.' : tab === 'Customers' ? 'Loyalty and supplier directory.' : tab === 'Reports' ? 'Store performance and sales analytics.' : 'People, permissions and activity history.'}</Text></View>}{content}</ScrollView>
    <View style={[s.bottomNav, { backgroundColor: c.surface, borderColor: c.border }]}>{(['Dashboard', 'Register', 'Inventory', 'More'] as const).map(item => { const selected = item === 'More' ? !(['Dashboard', 'Register', 'Inventory'].includes(tab)) : tab === item; const icon: IconName = item === 'Dashboard' ? 'view-dashboard-outline' : item === 'Register' ? 'point-of-sale' : item === 'Inventory' ? 'package-variant-closed' : 'menu'; return <Pressable key={item} onPress={() => item === 'More' ? setModal('menu') : setTab(item)} style={s.navItem}><View style={[s.navIcon, selected && { backgroundColor: c.primarySoft }]}><Icon c={c} name={icon} size={21} color={selected ? c.primary : c.muted} /></View><Text style={[s.navLabel, { color: selected ? c.primary : c.muted }]}>{item}</Text></Pressable>; })}</View>

    <Modal visible={modal === 'menu'} transparent animationType="slide" onRequestClose={hideMenu}><View style={s.overlay}><Pressable style={s.backdrop} onPress={hideMenu} /><View style={[s.menuSheet, { backgroundColor: c.surface }]}><View style={s.sheetHandle} /><View style={s.menuSheetHead}><View><Text style={[s.sectionTitle, { color: c.text }]}>Retail POS</Text><Text style={[s.mini, { color: c.muted }]}>Store Terminal #104</Text></View><Pressable onPress={hideMenu}><Icon c={c} name="close" /></Pressable></View><View style={[s.profileStrip, { backgroundColor: c.primarySoft }]}><View style={[s.avatar, { backgroundColor: c.surface }]}><Text style={{ color: c.primary, fontWeight: '900' }}>{user.name.split(' ').map(n => n[0]).join('').slice(0, 2)}</Text></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{user.name}</Text><Text style={[s.mini, { color: c.muted }]}>{user.role} · Active cashier</Text></View><Pressable onPress={() => { hideMenu(); setDark(!dark); }}><Icon c={c} name={dark ? 'weather-sunny' : 'weather-night'} color={c.primary} /></Pressable></View><View style={s.moduleGrid}>{modules.map(module => <Pressable key={module.name} onPress={() => { setTab(module.name); hideMenu(); }} style={[s.moduleCell, { borderColor: c.border, backgroundColor: tab === module.name ? c.primarySoft : c.bg }]}><Icon c={c} name={module.icon} color={tab === module.name ? c.primary : c.muted} size={21} /><Text style={[s.moduleText, { color: tab === module.name ? c.primary : c.text }]}>{module.name}</Text></Pressable>)}</View><Pressable onPress={goLogout} style={[s.logoutButton, { borderColor: '#FECACA' }]}><Icon c={c} name="logout" color={c.danger} /><Text style={{ color: c.danger, fontWeight: '800', marginLeft: 10 }}>Sign out / switch cashier</Text></Pressable></View></View></Modal>

    <Modal visible={modal === 'notifications'} transparent animationType="slide" onRequestClose={hideMenu}><View style={s.overlay}><Pressable style={s.backdrop} onPress={hideMenu} /><View style={[s.sheet, { backgroundColor: c.surface }]}><View style={s.sheetHandle} /><View style={s.sectionHead}><View><Text style={[s.sectionTitle, { color: c.text }]}>Notifications</Text><Text style={[s.mini, { color: c.muted }]}>{unread} unread alerts</Text></View><Pressable onPress={() => setStore(prev => ({ ...prev, notices: prev.notices.map(n => ({ ...n, read: true })) }))}><Text style={[s.link, { color: c.primary }]}>Mark all read</Text></Pressable></View>{store.notices.map(notice => <Pressable key={notice.id} onPress={() => setStore(prev => ({ ...prev, notices: prev.notices.map(n => n.id === notice.id ? { ...n, read: true } : n) }))} style={[s.noticeRow, { borderColor: c.border }]}><View style={[s.auditBullet, { backgroundColor: notice.read ? c.border : c.primary }]} /><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{notice.title}</Text><Text style={[s.mini, { color: c.muted }]}>{notice.body}</Text><Text style={[s.mini, { color: c.muted }]}>{fmtDate(notice.timestamp)}</Text></View></Pressable>)}</View></View></Modal>

    <Modal visible={modal === 'form'} transparent animationType="slide" onRequestClose={hideMenu}><View style={s.overlay}><Pressable style={s.backdrop} onPress={hideMenu} /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ width: '100%', justifyContent: 'flex-end' }}><View style={[s.sheet, { backgroundColor: c.surface }]}><View style={s.sheetHandle} /><View style={s.sectionHead}><Text style={[s.sectionTitle, { color: c.text }]}>{editingId ? 'Edit' : 'New'} {formKind === 'staff' ? 'team member' : formKind}</Text><Pressable onPress={hideMenu}><Icon c={c} name="close" /></Pressable></View><ScrollView style={{ maxHeight: 420 }} keyboardShouldPersistTaps="handled">{formFields.map(([label, key, keyboard]) => field(label, key, keyboard === 'numeric' ? 'numeric' : 'default'))}{formKind === 'purchase' && <View style={s.formStatus}><Text style={[s.fieldLabel, { color: c.text }]}>Receive stock now?</Text><Switch value={form.status !== 'PENDING'} onValueChange={value => setField('status', value ? 'RECEIVED' : 'PENDING')} trackColor={{ true: c.primary }} /></View>}</ScrollView><Pressable onPress={saveForm} style={[s.submitButton, { backgroundColor: c.primary }]}><Text style={s.submitText}>{formKind === 'purchase' ? 'Create purchase order' : 'Save changes'}</Text></Pressable></View></KeyboardAvoidingView></View></Modal>

    <Modal visible={modal === 'cart'} transparent animationType="slide" onRequestClose={hideMenu}><View style={s.overlay}><Pressable style={s.backdrop} onPress={hideMenu} /><View style={[s.sheet, { backgroundColor: c.surface }]}><View style={s.sheetHandle} /><View style={s.sectionHead}><View><Text style={[s.sectionTitle, { color: c.text }]}>Current sale</Text><Text style={[s.mini, { color: c.muted }]}>{cart.reduce((n, line) => n + line.quantity, 0)} items · {customer}</Text></View><Pressable onPress={hideMenu}><Icon c={c} name="close" /></Pressable></View>{cartRows.length === 0 ? <Empty c={c} title="Your cart is empty" text="Add products from the register to start a sale." /> : <><ScrollView style={{ maxHeight: 360 }}>{cartRows.map(({ line, product }) => <CartRow key={product.id} c={c} product={product} line={line} onStep={changeQty} />)}</ScrollView><View style={[divider(c.border), { marginVertical: 12 }]} /><View style={s.rowBetween}><Text style={[s.bodyText, { color: c.muted }]}>Subtotal</Text><Text style={[s.bodyText, { color: c.text }]}>{money(subtotal)}</Text></View><View style={s.rowBetween}><Text style={[s.bodyText, { color: c.muted }]}>Discount · tax included</Text><Text style={[s.bodyText, { color: c.danger }]}>−{money(itemDiscount + cartDiscountAmount)}</Text></View><View style={s.rowBetween}><Text style={[s.bodyText, { color: c.muted }]}>Tax</Text><Text style={[s.bodyText, { color: c.text }]}>{money(taxTotal)}</Text></View><View style={s.rowBetween}><Text style={[s.sectionTitle, { color: c.text }]}>Total due</Text><Text style={[s.sectionTitle, { color: c.primary }]}>{money(total)}</Text></View><View style={[s.rowBetween, { marginTop: 10 }]}><Text style={[s.mini, { color: c.muted }]}>Cart discount (%)</Text><TextInput keyboardType="decimal-pad" value={String(cartDiscount)} onChangeText={value => setCartDiscount(Math.max(0, Math.min(100, Number(value) || 0)))} style={[s.smallInput, { backgroundColor: c.bg, borderColor: c.border, color: c.text }]} /></View><Pressable onPress={() => { setTender(total.toFixed(2)); setPayment('CASH'); setModal('checkout'); }} style={[s.submitButton, { backgroundColor: c.primary, marginTop: 14 }]}><Text style={s.submitText}>Proceed to payment · {money(total)}</Text></Pressable></>}</View></View></Modal>

    <Modal visible={modal === 'checkout'} transparent animationType="slide" onRequestClose={hideMenu}><View style={s.overlay}><Pressable style={s.backdrop} onPress={hideMenu} /><View style={[s.sheet, { backgroundColor: c.surface }]}><View style={s.sheetHandle} /><View style={s.sectionHead}><View><Text style={[s.sectionTitle, { color: c.text }]}>Checkout & payment</Text><Text style={[s.mini, { color: c.muted }]}>{cartRows.length} line items</Text></View><Pressable onPress={() => setModal('cart')}><Text style={[s.link, { color: c.primary }]}>Back to cart</Text></Pressable></View><View style={[s.totalBar, { backgroundColor: c.primarySoft }]}><Text style={[s.rowTitle, { color: c.text }]}>Total payable</Text><Text style={[s.chartAmount, { color: c.primary }]}>{money(total)}</Text></View><Text style={[s.fieldLabel, { color: c.muted, marginTop: 16 }]}>PAYMENT METHOD</Text><View style={s.paymentGrid}>{[['CASH', 'cash'], ['CARD', 'credit-card-outline'], ['DIGITAL WALLET', 'cellphone-check'], ['BANK TRANSFER', 'bank-outline'], ['SPLIT', 'call-split']].map(([method, icon]) => <Pressable key={method} onPress={() => setPayment(method)} style={[s.paymentChoice, { borderColor: payment === method ? c.primary : c.border, backgroundColor: payment === method ? c.primarySoft : c.surface }]}><Icon c={c} name={icon as IconName} color={payment === method ? c.primary : c.muted} /><Text style={[s.mini, { color: payment === method ? c.primary : c.muted, fontWeight: '800' }]}>{method}</Text></Pressable>)}</View>{payment === 'CASH' && <View style={{ marginTop: 12 }}><Text style={[s.fieldLabel, { color: c.muted }]}>CASH RECEIVED</Text><TextInput keyboardType="decimal-pad" value={tender} onChangeText={setTender} style={[s.input, { backgroundColor: c.bg, borderColor: c.border, color: c.text }]} placeholder="Amount tendered" placeholderTextColor={c.muted} /><Text style={[s.bodyText, { color: c.success, marginTop: 7 }]}>Change due · {money(Math.max(0, (Number(tender) || 0) - total))}</Text></View>}{payment !== 'CASH' && <Text style={[s.subText, { color: c.muted, marginTop: 10 }]}>Payment of {money(total)} will be recorded as {payment.toLowerCase()}.</Text>}<Pressable onPress={finishSale} style={[s.submitButton, { backgroundColor: c.success, marginTop: 18 }]}><Text style={s.submitText}>Complete sale · {money(total)}</Text></Pressable></View></View></Modal>

    <Modal visible={modal === 'receipt'} transparent animationType="fade" onRequestClose={hideMenu}><View style={[s.receiptOverlay, { backgroundColor: 'rgba(3,10,25,.7)' }]}><View style={[s.receiptCard, { backgroundColor: c.surface }]}><View style={[s.receiptIcon, { backgroundColor: '#DCFCE7' }]}><Icon c={c} name="check-bold" color="#15803D" size={27} /></View><Text style={[s.pageTitle, { color: c.text, textAlign: 'center', marginTop: 10 }]}>Sale complete</Text><Text style={[s.subText, { color: c.muted, marginTop: 5 }]}>{receipt?.invoice} · {fmtDate(receipt?.timestamp || new Date().toISOString())}</Text><View style={[divider(c.border), { marginVertical: 15 }]} />{receipt?.items.map((item, i) => <View key={i} style={s.rowBetween}><Text style={[s.bodyText, { color: c.muted, flex: 1 }]}>{item.quantity} × {item.name}</Text><Text style={[s.bodyText, { color: c.text }]}>{money(item.price * item.quantity)}</Text></View>)}<View style={[divider(c.border), { marginVertical: 14 }]} /><View style={s.rowBetween}><Text style={[s.sectionTitle, { color: c.text }]}>Total paid</Text><Text style={[s.chartAmount, { color: c.primary }]}>{money(receipt?.total || 0)}</Text></View><Text style={[s.mini, { color: c.muted, textAlign: 'center', marginTop: 8 }]}>{receipt?.method} · Change {money(receipt?.change || 0)}</Text><Pressable onPress={() => Share.share({ title: 'Retail POS receipt', message: `RETAIL POS · DOWNTOWN TERMINAL\n${receipt?.invoice}\n${receipt?.items.map(item => `${item.quantity} × ${item.name} — ${money(item.price * item.quantity)}`).join('\n')}\n\nTOTAL ${money(receipt?.total || 0)} · ${receipt?.method}` })} style={[s.secondaryButton, { borderColor: c.border }]}><Icon c={c} name="share-variant-outline" color={c.primary} /><Text style={[s.buttonLabel, { color: c.text }]}>Share digital receipt</Text></Pressable><Pressable onPress={() => setModal(null)} style={[s.submitButton, { backgroundColor: c.primary, marginTop: 10 }]}><Text style={s.submitText}>Done</Text></Pressable></View></View></Modal>
  </View>;
}

function Icon({ c, name, color, size = 19 }: { c: Record<string, string>; name: IconName; color?: string; size?: number }) { return <MaterialCommunityIcons name={name} size={size} color={color || c.muted} />; }
function Login({ c, loginName, loginPin, setLoginName, setLoginPin, error, onLogin, dark, setDark }: { c: Record<string, string>; loginName: string; loginPin: string; setLoginName: (x: string) => void; setLoginPin: (x: string) => void; error: string; onLogin: () => void; dark: boolean; setDark: (x: boolean) => void }) {
  return <ScrollView contentContainerStyle={s.loginWrap} keyboardShouldPersistTaps="handled"><View style={s.loginTools}><Text style={[s.mini, { color: c.muted }]}>STORE TERMINAL #104</Text><Pressable onPress={() => setDark(!dark)} style={[s.iconBtnSmall, { backgroundColor: c.surface }]}><Icon c={c} name={dark ? 'weather-sunny' : 'weather-night'} /></Pressable></View><View style={[s.brandMark, { backgroundColor: c.primary }]}><Icon c={c} name="point-of-sale" color="#fff" size={37} /></View><Text style={[s.loginTitle, { color: c.text }]}>RETAIL POS</Text><Text style={[s.subText, { color: c.muted, textAlign: 'center' }]}>Enterprise point of sale & retail management</Text><View style={[s.localPill, { backgroundColor: '#DCFCE7' }]}><View style={[s.auditBullet, { backgroundColor: '#10B981' }]} /><Text style={{ color: '#166534', fontSize: 11, fontWeight: '800' }}>LOCAL STORE · OFFLINE READY</Text></View><View style={[s.loginCard, { backgroundColor: c.surface, borderColor: c.border }]}><Text style={[s.sectionTitle, { color: c.text, textAlign: 'center' }]}>Cashier & staff sign in</Text><Text style={[s.subText, { color: c.muted, textAlign: 'center', marginTop: 5 }]}>Enter your terminal username and PIN.</Text><Text style={[s.fieldLabel, { color: c.muted, marginTop: 20 }]}>USERNAME</Text><TextInput autoCapitalize="none" value={loginName} onChangeText={setLoginName} placeholder="Enter username" placeholderTextColor={c.muted} style={[s.input, { backgroundColor: c.bg, borderColor: c.border, color: c.text }]} /><Text style={[s.fieldLabel, { color: c.muted, marginTop: 14 }]}>SECURITY PIN</Text><TextInput value={loginPin} onChangeText={setLoginPin} secureTextEntry keyboardType="number-pad" placeholder="Enter PIN" placeholderTextColor={c.muted} style={[s.input, { backgroundColor: c.bg, borderColor: c.border, color: c.text }]} onSubmitEditing={onLogin} />{error ? <Text style={{ color: c.danger, marginTop: 10, fontSize: 12 }}>{error}</Text> : null}<Pressable onPress={onLogin} style={[s.submitButton, { backgroundColor: c.primary, marginTop: 20 }]}><Text style={s.submitText}>Sign in to terminal</Text><Icon c={c} name="arrow-right" color="#fff" /></Pressable><View style={[divider(c.border), { marginVertical: 16 }]} /><Text style={[s.mini, { color: c.muted, textAlign: 'center' }]}>DEMO ACCESS · ADMIN / 1234</Text></View><Text style={[s.mini, { color: c.muted, marginTop: 20, textAlign: 'center' }]}>Retail POS · React Native with Expo · Local data is saved on this device</Text></ScrollView>;
}
function Metric({ c, icon, label, value, delta, tint, onPress }: { c: Record<string, string>; icon: IconName; label: string; value: string; delta: string; tint: string; onPress?: () => void }) { return <Pressable onPress={onPress} style={[s.metricCard, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.metricIcon, { backgroundColor: tint }]}><Icon c={c} name={icon} color={blue} size={19} /></View><Text style={[s.metricLabel, { color: c.muted }]}>{label}</Text><Text style={[s.metricValue, { color: c.text }]}>{value}</Text><Text style={[s.metricDelta, { color: c.success }]}>{delta}</Text></Pressable>; }
function SearchBox({ c, value, onChange, placeholder }: { c: Record<string, string>; value: string; onChange: (x: string) => void; placeholder: string }) { return <View style={[s.searchBox, { backgroundColor: c.surface, borderColor: c.border }]}><MaterialCommunityIcons name="magnify" size={19} color={c.muted} /><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={c.muted} style={[s.searchInput, { color: c.text }]} /><MaterialCommunityIcons name="barcode-scan" size={19} color={c.muted} /></View>; }
function Chip({ c, active, label, onPress }: { c: Record<string, string>; active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[s.chip, { backgroundColor: active ? c.primary : c.surface, borderColor: active ? c.primary : c.border }]}><Text style={{ color: active ? '#fff' : c.muted, fontSize: 12, fontWeight: '700' }}>{label}</Text></Pressable>; }
function Badge({ label, good, c }: { label: string; good: boolean; c: Record<string, string> }) { return <View style={[s.pill, { backgroundColor: good ? '#DCFCE7' : '#FEF3C7' }]}><Text style={{ color: good ? '#15803D' : '#B45309', fontSize: 10, fontWeight: '900' }}>{label}</Text></View>; }
function ProductRow({ c, product, subline, trailing, onPress }: { c: Record<string, string>; product: Product; subline?: string; trailing?: React.ReactNode; onPress?: () => void }) { return <Pressable onPress={onPress} style={[s.productRow, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.productThumb, { backgroundColor: product.category === 'Electronics' ? '#EDE9FE' : '#DBEAFE' }]}><Text style={{ fontSize: 22 }}>{product.category === 'Beverages' ? '☕' : product.category === 'Electronics' ? '🎧' : product.category === 'Dairy & Fresh' ? '🥛' : product.category === 'Snacks' ? '🍫' : '🛍️'}</Text></View><View style={{ flex: 1, paddingRight: 8 }}><Text style={[s.rowTitle, { color: c.text }]} numberOfLines={1}>{product.name}</Text><Text style={[s.mini, { color: c.muted }]}>{subline || `SKU ${product.sku} · ${product.category}`}</Text><Text style={[s.productPrice, { color: c.primary, marginTop: 5 }]}>{money(product.price)} <Text style={[s.mini, { color: c.muted, fontWeight: '500' }]}>· Stock {product.stock}</Text></Text></View>{trailing}</Pressable>; }
function CartRow({ c, product, line, onStep }: { c: Record<string, string>; product: Product; line: CartLine; onStep: (id: string, step: number) => void }) { return <View style={[s.cartRow, { borderColor: c.border }]}><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{product.name}</Text><Text style={[s.mini, { color: c.muted }]}>{money(product.price)} each{line.discount ? ` · ${line.discount}% off` : ''}</Text></View><View style={s.stockActions}><Pressable onPress={() => onStep(product.id, -1)} style={[s.stepButton, { backgroundColor: c.bg }]}><Icon c={c} name="minus" size={15} /></Pressable><Text style={[s.rowTitle, { color: c.text, minWidth: 22, textAlign: 'center' }]}>{line.quantity}</Text><Pressable onPress={() => onStep(product.id, 1)} style={[s.stepButton, { backgroundColor: c.primarySoft }]}><Icon c={c} name="plus" color={c.primary} size={15} /></Pressable><Text style={[s.rowTitle, { color: c.text, minWidth: 64, textAlign: 'right' }]}>{money(product.price * (1 - line.discount / 100) * line.quantity)}</Text></View></View>; }
function SaleRow({ c, sale, trailing, onPress }: { c: Record<string, string>; sale: Sale; trailing?: React.ReactNode; onPress?: () => void }) { return <Pressable onPress={onPress} style={[s.saleRow, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.iconSquare, { backgroundColor: '#DBEAFE' }]}><MaterialCommunityIcons name="receipt-text-outline" color={blue} size={20} /></View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.text }]}>{sale.invoice} · {sale.customer}</Text><Text style={[s.mini, { color: c.muted }]}>{fmtDate(sale.timestamp)} · {sale.items.length} items · {sale.method}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={[s.rowTitle, { color: c.text }]}>{money(sale.total)}</Text><Text style={[s.mini, { color: sale.status === 'COMPLETED' ? green : '#B91C1C', fontWeight: '800' }]}>{sale.status}</Text></View>{trailing}</Pressable>; }
function ProgressLine({ c, title, total, maximum, tint }: { c: Record<string, string>; title: string; total: number; maximum: number; tint: string }) { return <View style={{ marginBottom: 15 }}><View style={s.rowBetween}><Text style={[s.bodyText, { color: c.text }]}>{title}</Text><Text style={[s.bodyText, { color: c.text }]}>{money(total)}</Text></View><View style={[s.progressTrack, { backgroundColor: c.raised }]}><View style={{ width: `${Math.min(100, total / Math.max(1, maximum) * 100)}%`, height: '100%', borderRadius: 5, backgroundColor: tint }} /></View></View>; }
function Empty({ c, title, text }: { c: Record<string, string>; title: string; text: string }) { return <View style={[s.empty, { backgroundColor: c.surface, borderColor: c.border }]}><MaterialCommunityIcons name="tray-alert" size={27} color={c.muted} /><Text style={[s.rowTitle, { color: c.text, marginTop: 8 }]}>{title}</Text><Text style={[s.subText, { color: c.muted, textAlign: 'center', marginTop: 4 }]}>{text}</Text></View>; }

const s = StyleSheet.create({
  root: { flex: 1, paddingTop: Platform.OS === 'android' ? NativeStatusBar.currentHeight || 0 : 0 },
  topBar: { minHeight: 62, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, gap: 9 },
  menuBtn: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, topTitle: { fontSize: 17, fontWeight: '900' }, topSubtitle: { fontSize: 10, fontWeight: '600', marginTop: 2 },
  iconBtn: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22 }, iconBtnSmall: { width: 37, height: 37, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }, notificationDot: { position: 'absolute', top: 2, right: 0, minWidth: 16, height: 16, paddingHorizontal: 3, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#DC2626' }, dotText: { fontSize: 9, color: '#fff', fontWeight: '900' }, smallDot: { position: 'absolute', width: 7, height: 7, top: 7, right: 8, borderRadius: 4 },
  scrollContent: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 28 }, pageHeading: { marginBottom: 16 }, pageTitle: { fontSize: 23, fontWeight: '900', letterSpacing: -0.4 }, bigTitle: { fontSize: 22, fontWeight: '900', marginTop: 5, letterSpacing: -0.4 }, subText: { fontSize: 12, lineHeight: 18 }, eyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 1.3 }, storeHeadline: { flexDirection: 'row', alignItems: 'center', marginBottom: 17 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, metricCard: { width: '48.4%', minHeight: 138, borderRadius: 16, borderWidth: 1, padding: 13 }, metricIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center', marginBottom: 9 }, metricLabel: { fontSize: 11, fontWeight: '700' }, metricValue: { fontSize: 21, fontWeight: '900', marginTop: 3 }, metricDelta: { fontSize: 10, fontWeight: '700', marginTop: 5 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 20, marginBottom: 10, gap: 8 }, sectionTitle: { fontSize: 15, fontWeight: '900' }, link: { fontSize: 12, fontWeight: '800' }, quickGrid: { gap: 9 }, quickAction: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 12, borderRadius: 14, borderWidth: 1 }, iconSquare: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, quickText: { flex: 1, fontSize: 13, fontWeight: '800' },
  chartCard: { borderWidth: 1, borderRadius: 17, padding: 15 }, chartTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cardLabel: { fontSize: 11, fontWeight: '700' }, chartAmount: { fontSize: 25, fontWeight: '900' }, pill: { borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 }, chartBars: { height: 83, flexDirection: 'row', alignItems: 'stretch', gap: 4, marginTop: 15 }, chartLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 7 }, mini: { fontSize: 10, lineHeight: 15 },
  saleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 11, borderRadius: 14, borderWidth: 1, marginBottom: 8 }, rowTitle: { fontSize: 12, fontWeight: '800' }, productPrice: { fontSize: 14, fontWeight: '900' }, tinyAction: { borderRadius: 9, paddingVertical: 7, paddingHorizontal: 9 }, tinyActionText: { fontSize: 10, fontWeight: '800' },
  customerSelector: { minHeight: 55, flexDirection: 'row', alignItems: 'center', padding: 9, gap: 9, borderRadius: 13, borderWidth: 1, marginBottom: 10 }, avatar: { width: 38, height: 38, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  searchBox: { height: 46, borderWidth: 1, borderRadius: 13, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 9 }, searchInput: { flex: 1, fontSize: 13, paddingVertical: 5 }, chipsRow: { flexDirection: 'row', gap: 7, paddingVertical: 5, alignItems: 'center' }, chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, borderWidth: 1 },
  productGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, productTile: { width: '48.5%', borderRadius: 15, borderWidth: 1, padding: 10, minHeight: 160 }, productEmoji: { width: 45, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, productName: { fontSize: 11, fontWeight: '800', lineHeight: 15, minHeight: 30 }, productTileFoot: { marginTop: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, plusCircle: { width: 25, height: 25, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  productRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderRadius: 14, borderWidth: 1, marginBottom: 8 }, productThumb: { width: 43, height: 43, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, stockTag: { fontSize: 9, fontWeight: '900', marginBottom: 6 }, stockActions: { flexDirection: 'row', alignItems: 'center', gap: 6 }, stepButton: { width: 27, height: 27, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  inventoryTotals: { flexDirection: 'row', gap: 8, marginBottom: 10 }, inventoryTotal: { flex: 1, minHeight: 78, padding: 10, justifyContent: 'center', borderRadius: 13, borderWidth: 1 },
  primaryAction: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 }, primaryActionText: { color: '#fff', fontSize: 11, fontWeight: '900' },
  aiBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderRadius: 15 }, chatBox: { padding: 11, borderRadius: 15, borderWidth: 1, gap: 9, marginTop: 9 }, chatBubble: { maxWidth: '90%', padding: 11, borderRadius: 13, borderWidth: 1 }, dealMini: { marginTop: 8, borderWidth: 1, borderRadius: 11, padding: 9, gap: 6 }, addDealBtn: { alignSelf: 'flex-start', borderRadius: 8, paddingVertical: 6, paddingHorizontal: 9 }, dealCard: { borderWidth: 1, padding: 12, borderRadius: 15, marginBottom: 9, gap: 9 }, dealCardTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, dealFoot: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  listCard: { borderWidth: 1, borderRadius: 15, padding: 12, marginBottom: 9 }, listCardTop: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 11 }, rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, bodyText: { fontSize: 12 },
  segment: { flexDirection: 'row', borderRadius: 12, padding: 4, marginBottom: 4 }, segmentItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 9, borderRadius: 9 }, segmentText: { fontSize: 12, fontWeight: '800' }, personCard: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 11, borderWidth: 1, borderRadius: 14, marginBottom: 8 },
  reportHero: { borderRadius: 18, padding: 18, marginTop: 12, marginBottom: 12 }, progressTrack: { height: 8, borderRadius: 5, overflow: 'hidden', marginTop: 7 }, auditRow: { flexDirection: 'row', paddingVertical: 11, gap: 10, borderBottomWidth: StyleSheet.hairlineWidth }, auditBullet: { width: 8, height: 8, borderRadius: 5, marginTop: 4 }, noticeRow: { flexDirection: 'row', gap: 10, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  bottomNav: { minHeight: 65, paddingBottom: Platform.OS === 'ios' ? 11 : 2, flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: StyleSheet.hairlineWidth }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2 }, navIcon: { width: 48, height: 30, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, navLabel: { fontSize: 9, fontWeight: '800' },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,10,24,.25)' }, backdrop: { ...StyleSheet.absoluteFill }, sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 18, paddingBottom: 30, maxHeight: '90%' }, menuSheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 18, paddingBottom: 30, minHeight: '77%' }, sheetHandle: { width: 42, height: 4, borderRadius: 3, backgroundColor: '#94A3B8', alignSelf: 'center', marginBottom: 15 }, menuSheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 }, profileStrip: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 10, borderRadius: 13 }, moduleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 }, moduleCell: { width: '31.4%', minHeight: 76, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center', gap: 6, padding: 6 }, moduleText: { fontSize: 10, fontWeight: '800', textAlign: 'center' }, logoutButton: { minHeight: 46, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderRadius: 12, marginTop: 'auto' },
  fieldLabel: { fontSize: 10, fontWeight: '900', letterSpacing: .5, marginBottom: 6 }, input: { height: 44, borderWidth: 1, borderRadius: 11, paddingHorizontal: 11, fontSize: 13 }, smallInput: { width: 58, height: 34, borderWidth: 1, borderRadius: 9, paddingHorizontal: 8, textAlign: 'center' }, formStatus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 5 }, submitButton: { minHeight: 48, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 12 }, submitText: { color: '#fff', fontWeight: '900', fontSize: 13 }, paymentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 8 }, paymentChoice: { minWidth: '30%', borderWidth: 1, borderRadius: 11, paddingVertical: 10, paddingHorizontal: 9, alignItems: 'center', gap: 5 }, totalBar: { borderRadius: 13, padding: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cartRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 8 }, empty: { alignItems: 'center', padding: 22, borderWidth: 1, borderRadius: 14 }, receiptOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 }, receiptCard: { width: '100%', borderRadius: 20, padding: 18 }, receiptIcon: { alignSelf: 'center', width: 54, height: 54, borderRadius: 30, alignItems: 'center', justifyContent: 'center' }, secondaryButton: { height: 44, borderWidth: 1, borderRadius: 11, marginTop: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, buttonLabel: { fontWeight: '800', fontSize: 12 },
  loginWrap: { flexGrow: 1, padding: 22, alignItems: 'center', justifyContent: 'center' }, loginTools: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 27 }, brandMark: { width: 72, height: 72, borderRadius: 23, alignItems: 'center', justifyContent: 'center' }, loginTitle: { fontSize: 27, fontWeight: '900', letterSpacing: 1.4, marginTop: 12 }, localPill: { flexDirection: 'row', alignItems: 'center', gap: 7, borderRadius: 20, paddingHorizontal: 11, paddingVertical: 7, marginTop: 14 }, loginCard: { width: '100%', borderWidth: 1, borderRadius: 18, padding: 17, marginTop: 23 },
});
